---
name: Test and cache flake

"on":
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@main
      - uses: determinatesystems/flake-checker-action@main
      - uses: determinatesystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated

  flake-change:
    runs-on: ubuntu-latest
    needs: update
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changed:
              - 'flake.*'

  archive:
    needs: flake-change
    if: ${{ needs.flake-change.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: percygtdev
      - name: Archive flake inputs
        run: nix flake archive --json
      - name: Ready to build
        run: echo "make-build=yes" >> "$GITHUB_OUTPUT"

  build:
    needs: archive
    if: ${{ needs.archive.outputs.make-build == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: percygtdev
      - name: Build packages
        run: nix flake show --json | jq  '.packages."x86_64-linux"|keys[]'| xargs -I {} nix build --json --no-link --print-build-logs .#{}
