---
name: Update flake.lock

"on":
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Update lock
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          nix flake update --commit-lock-file
          git push
